version: "2"

run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - goimports
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

